### ISSUE TITLE
final content & ui todo

### ISSUE THREAD

**Issue by lynxlynxlynx** [gemrb/gemrb.github.io#11]
which features from the theme can we use to our advantage?
- [x] Search (reenable travis, fix error; algalia is set up)
- [x] more? https://mmistakes.github.io/minimal-mistakes/docs/helpers/
- [x] feature rows? https://mmistakes.github.io/minimal-mistakes/docs/helpers/#feature-row
- [x] gallery https://mmistakes.github.io/minimal-mistakes/docs/helpers/#gallery

is anything missing markdown styling?

should we use highlights somewhere https://mmistakes.github.io/minimal-mistakes/docs/utility-classes/#notices ?

would more font awesome icons make it better? https://fontawesome.com/icons?d=gallery&m=free

~would a sidebar on the left (everywhere?) help? https://mmistakes.github.io/minimal-mistakes/docs/navigation/#custom-sidebar-navigation-menu https://mmistakes.github.io/minimal-mistakes/docs/helpers/#navigation-list~

which pages need finalization:
- [x] api docs #9 
  - [x] jekyll layout for the pages, to automatically include a link to the index and intro
- [x] install: config and run section update
- [x] install: windows content
- [x] fix the outline https://github.com/mmistakes/minimal-mistakes/issues/2502
- [x] innovations: content update
- [x] fix opengraph fallback image
- [x] index:  styling
- [x] index: finish content,
- [x] install: styling
- [x] history: to be written
- [x] features: table styling,
- [x] add all favicons, maybe https://realfavicongenerator.net/  https://github.com/afaundez/jekyll-favicon
- [x] fix favicon path
- [x] fix header logo
- [x] fix header image
- [x] media: gallery
- [x] footer: add "edit this page" link
- [x] cheats: perhaps style the key combos
- [x] cheats: GUIScript self-reference
- [x] innovations: split into sections
- [x] features:  bring feature list closer
- [x] feedback: toc
- [x] Common problems: redundant minitoc and title
- [x] index:  toc?,
- [x] install: compilation mislink
- [x] installing the games: toc
- [x] GUI-structure: func links need at least .md/.html suffixes
- [x] faq: toc
- [x] new game: duplicate title, garbage in toc
